# Generated by Django 3.0.8 on 2020-07-07 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_time', models.DateField(default=django.utils.timezone.now)),
                ('data', models.TextField(max_length=300)),
                ('category', models.CharField(choices=[('Hiking', 'Hiking'), ('Rafting', 'Rafting'), ('Treking', 'Treking'), ('Roadtrips', 'Roadtrips')], max_length=50)),
            ],
        ),
    ]
